run:
  timeout: 5m
  issues-exit-code: 1
  tests: true

linters:
  enable:
    - gosimple
    - govet
    - ineffassign
    - unused
    - misspell
    - gofmt
    - goimports
    - errcheck
    - goconst
    - gocyclo
    - staticcheck
  
  disable:

output:
  formats:
    - format: colored-line-number
  print-issued-lines: true
  print-linter-name: true
